### ISSUE TITLE
License inconsistency

### ISSUE THREAD

**Issue by juliangilbey** [nfroidure/VarStream#7]
Hi! The LICENCE file says this project is licenced under the MIT licence, but the three files in src all specify GPL 3 instead. Is this intentional, or did you intend for those three files also to be MIT-licenced?

**Comment by nfroidure** [comment]
Hi @juliangilbey . This is a very old project. Despite the fact I find the approach is still relevant, it never gained any traction. So to answer you request. Yes I wanted to push it as an MIT project, but I don't think it is a good thing to use except if you plan to take the lead of the project and in this case, I can transfer the ownership.

**Comment by juliangilbey** [comment]
Hi @nfroidure! Thanks for such a quick reply. It turns out that webfont depends on svgicons2svgfont, which has neatequal in its tests, which in turn depends on varstream. So that's how come I'm using it. I doubt that neatequal is used much elsewhere.

**Comment by nfroidure** [comment]
Wieird, `neatequal` is supposed to be a dev dependency.

**Comment by juliangilbey** [comment]
Indeed it is; I'm building a Debian package for webfont, and I run as many of the package tests as I can during the build to check things are working correctly, hence why I included neatequal.

**Comment by nfroidure** [comment]
I understand, I'll try to fix it when I'll have some time to do it. Would merge any PR in the meanwhile of course.
